#!/bin/bash

# Borrar archivos con extensión .out y .exe
find . -type f -name '*.out' -delete
find . -type f -name '*.exe' -delete

# Añadir todos los cambios al staging area
git add .

# Generar un número aleatorio
NUMERO_ALEATORIO=$RANDOM

# Realizar el commit con un mensaje que incluya el número aleatorio
git commit -m "$NUMERO_ALEATORIO"

# Hacer push de los cambios al repositorio remoto
git push
